#%RAML 1.0 Library
types:
  get-pint:
    type: object
    properties:
      status:
        type: string
        example: OK
        required: false
      apiName:
        type: string
        example: service-cloud-system-api
        required: false
      apiVersion:
        type: string
        example: 1.3.0
        required: false
      timestamp:
        type: datetime
        example: '2020-08-01T13:15:25.000Z'
        required: false
      correlationId:
        type: string
        example: 1c7968f0-3102-11eb-adc1-0242ac120002
        required: false
      dependencies:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
              example: Salesforce
              required: false
            status:
              type: string
              example: UP
              required: false