#%RAML 1.0 Library
types:
  get-all-cases:
    type: object
    properties:
      count:
        type: integer
        example: 1
        required: false
      hits:
        type: array
        items:
          type: object
          properties:
            Origin:
              type: string
              example: Email
              required: false
            LastModifiedDate:
              type: datetime
              example: '2022-11-08T14:02:49.000Z'
              required: false
            AccountId:
              type: string
              example: 'null'
              required: false
            Description:
              type: string
              example: Product is not working properly.
              required: false
            SuppliedCompany:
              type: string
              example: 'null'
              required: false
            LastReferencedDate:
              type: datetime
              example: '2022-11-08T14:23:22.000Z'
              required: false
            ContactId:
              type: string
              example: 0034x00001I71rbAAB
              required: false
            IsClosed:
              type: string
              example: 'false'
              required: false
            type:
              type: string
              example: Case
              required: false
            Reason:
              type: string
              example: Performance
              required: false
            ContactPhone:
              type: string
              example: 845-304-6598
              required: false
            SuppliedEmail:
              type: string
              example: dianedeluna@email.com
              required: false
            CreatedById:
              type: string
              example: 0054x000006CGhsAAG
              required: false
            OwnerId:
              type: string
              example: 0054x000006CGhsAAG
              required: false
            SuppliedName:
              type: string
              example: 'null'
              required: false
            SuppliedPhone:
              type: string
              example: 'null'
              required: false
            CaseNumber:
              type: string
              example: '00001026'
              required: false
            ContactFax:
              type: string
              example: 'null'
              required: false
            MasterRecordId:
              type: string
              example: 'null'
              required: false
            ContactMobile:
              type: string
              example: 803-283-1927
              required: false
            ParentId:
              type: string
              example: 'null'
              required: false
            Status:
              type: string
              example: Working
              required: false
            IsDeleted:
              type: string
              example: 'false'
              required: false
            Comments:
              type: string
              example: 'null'
              required: false
            Priority:
              type: string
              example: High
              required: false
            LastViewedDate:
              type: datetime
              example: '2022-11-08T14:23:22.000Z'
              required: false
            Subject:
              type: string
              example: Product malfunction
              required: false
            SystemModstamp:
              type: datetime
              example: '2022-11-08T14:02:49.000Z'
              required: false
            Type:
              type: string
              example: Electronic
              required: false
            IsEscalated:
              type: string
              example: 'false'
              required: false
            CreatedDate:
              type: datetime
              example: '2022-09-28T14:09:30.000Z'
              required: false
            ContactEmail:
              type: string
              example: dianedeluna@email.com
              required: false
            Id:
              type: string
              example: 5004x00000MdOqzAAF
              required: false
            ClosedDate:
              type: string
              example: 'null'
              required: false
            AssetId:
              type: string
              example: 'null'
              required: false
            LastModifiedById:
              type: string
              example: 0054x000006CGhsAAG
              required: false
      start:
        type: integer
        example: 0
        required: false
      total:
        type: integer
        example: 1
        required: false