#%RAML 1.0 Library

types:
  get-all-opportunitys:
    type: object
    properties:
      count:
        type: integer
        example: 7
        required: false
      hits:
        type: array
        items:
          type: object
          properties:
            firstName:
              type: string
              example: Carole
              required: false
            lastName:
              type: string
              example: White (Sample)
              required: false
            email:
              type: string
              example: info@salesforce.com
              required: false
            id:
              type: string
              example: 003Hs00004aSfN6IAK
              required: false
            name:
              type: string
              example: Carole White (Sample)
              required: false
            phone:
              type: string
              example: 1 (800) 667-6389
              required: false
            mobilePhone:
              type: string
              example: 803-283-1927
              required: false
      start:
        type: integer
        example: 0
        required: false
      total:
        type: integer
        example: 1
        required: false