#%RAML 1.0 Library

types:
  patch-opportunity:
    type: object
    properties:
      sucess:
        type: boolean
        example: true
        required: false
      message:
        type: string
        example: Opportunity 00003501/0034x00001I71rbAAB updated
        required: false