#%RAML 1.0 Library

types:
  patch-opportunity:
    type: array
      sucess:
        type: boolean
        example: true
        required: false
      message:
        type: string
        example: Customer/Contact 00003501/0034x00001I71rbAAB updated
        required: false