#%RAML 1.0 Library
usage: Common RAML Fragments to standardise implementation of common aspects of RAML API Specifications.

#Ensure no existing traits or datatypes are updated with a breaking change if possible, they could be used by any number of services that could be affected. Ensure to use semantic versioning when publishing this fragment.

traits:
  request-get-all-cases: !include traits/request-get-all-cases.raml
  request-get-all-contacts: !include traits/request-get-all-contacts.raml
  request-get-cases-by-params: !include traits/request-get-cases-by-params.raml
  request-get-contact-by-params: !include traits/request-get-contact-by-params.raml
  request-get-ping: !include traits/request-get-ping.raml
  request-patch-opportunity: !include traits/request-patch-opportunity.raml
  request-put-contact-by-contactId: !include traits/request-put-contact-by-contactId.raml

resourceTypes:
  global-test: !include libraries/global-type-library.raml