#%RAML 1.0 Library
usage: This library defines all OSF Accelerator resources

types:
  # Salesforce Service Cloud
  Case: !include dataTypes/service/Case.raml
  CasesResponse: !include dataTypes/service/CasesResponse.raml
  Contact: !include dataTypes/service/Contact.raml
  ContactsResponse: !include dataTypes/service/ContactsResponse.raml
  
  # Salesforce Commerce Cloud
  Order: !include dataTypes/commerce/Order.raml
  OrdersResponse: !include dataTypes/commerce/OrdersResponse.raml
  Customer: !include dataTypes/commerce/Customer.raml
  CustomersResponse: !include dataTypes/commerce/CustomersResponse.raml
  
  # OSF Accelerators
  CustomerSummary: !include dataTypes/common/CustomerSummary.raml
  Profile: !include dataTypes/common/Profile.raml
  ProfilesResponse: !include dataTypes/common/ProfilesResponse.raml
 
  # Global resources
  PingResponse: !include dataTypes/global/PingResponse.raml
  UpdateResponse: !include dataTypes/global/UpdateResponse.raml
  PaginatedPartialResponse: !include dataTypes/global/PaginatedPartialResponse.raml

  # Traits
traits:
  GlobalErrorResponse: !include traits/global/GlobalErrorResponse.raml
  ClientIdRequired: !include traits/global/ClientIdEnforcement.raml
  Jwt: !include traits/global/Jwt.raml