#%RAML 1.0 ResourceType

traits:
  test: ../traits/request-put-contact-by-contactId.raml
uriParameters:
  contactId:
    description: Specifies the unique identifier for the contact's account.
    example: 0034x00001I71rbAAB
    type: string
put:
  is:[]