#%RAML 1.0 DataType 
type: object
properties:
  error:
    type: object
    properties:
      code:
        type: integer
      reason:
        type: string
      apiName:
        type: string
      correlationId:
        type: string
      dateTime:
        type: string
      message:
        type: object
        properties:
          description?:
            type: string