#%RAML 1.0 DataType
type: array
description: Represents a dependency status result for ping responses
items:
  properties:
    name: 
      description: Logical name of the connection (e.g., system name)
      type: string
    status:
      description: Status of the connection, identifying whether the connection was validated (UP), the connection timed out (DOWN), or the connection attempt failed for some other reason (ERROR)
      enum: [ "UP", "DOWN", "ERROR" ]
