#%RAML 1.0 NamedExample
value: {
  "firstName": "Diane",
  "lastName": "Deluna",
  "email": "dianedeluna@email.com",
  "phone": "673-657-1633",
  "homePhone": "233-657-1123",
  "mobilePhone": "432-245-4543",
  "businessPhone": "865-323-3567",
  "otherPhone": "235-123-3234",
  "customerId": "abkGgOEr01x9PChQpmC4AjiOGe",
  "contactId": "0034x00001I71rbAAB",
  "name": "Diane Deluna",
  "customerNo": "00003501"
}