#%RAML 1.0 NamedExample
value: {
  "count": 1,
  "hits": [
      {
          "Origin": "Email",
          "LastModifiedDate": "2022-11-08T14:02:49.000Z",
          "AccountId": "null",
          "Description": "Product is not working properly.",
          "SuppliedCompany": "null",
          "LastReferencedDate": "2022-11-08T14:23:22.000Z",
          "ContactId": "0034x00001I71rbAAB",
          "IsClosed": "false",
          "type": "Case",
          "Reason": "Performance",
          "ContactPhone": "845-304-6598",
          "SuppliedEmail": "dianedeluna@email.com",
          "CreatedById": "0054x000006CGhsAAG",
          "OwnerId": "0054x000006CGhsAAG",
          "SuppliedName": "null",
          "SuppliedPhone": "null",
          "CaseNumber": "00001026",
          "ContactFax": "null",
          "MasterRecordId": "null",
          "ContactMobile": "803-283-1927",
          "ParentId": "null",
          "Status": "Working",
          "IsDeleted": "false",
          "Comments": "null",
          "Priority": "High",
          "LastViewedDate": "2022-11-08T14:23:22.000Z",
          "Subject": "Product malfunction",
          "SystemModstamp": "2022-11-08T14:02:49.000Z",
          "Type": "Electronic",
          "IsEscalated": "false",
          "CreatedDate": "2022-09-28T14:09:30.000Z",
          "ContactEmail": "dianedeluna@email.com",
          "Id": "5004x00000MdOqzAAF",
          "ClosedDate": "null",
          "AssetId": "null",
          "LastModifiedById": "0054x000006CGhsAAG"
      }
  ],
  "start": 0,
  "total": 1
}