#%RAML 1.0 NamedExample
value: {
  "count": 1,
  "hits": [
    {
  "firstName": "Diane",
  "lastName": "Deluna",
  "email": "dianedeluna@email.com",
  "id": "0034x00001I71rbAAB",
  "name": "Diane Deluna",
  "phone": "845-304-6598",
  "homePhone": "037-231-3911",
  "mobilePhone": "803-283-1927",
  "otherPhone": "821-303-8362"
    }
  ],
  "start": 0,
  "total": 1
}