#%RAML 1.0 Trait

uses:
  response-ping: ../types/responses/get-ping.raml
displayName: healthCheck
queryParameters:
  checkDependencies?:
    description: Set to true to check and report status of all dependencies, such as system connections and downstream APIs; default is false
    type: boolean
responses:
  200:
    body:
      application/json:
        type: response-ping.get-ping
        example: !include ../examples/responses/get-ping.json