#%RAML 1.0 Trait

uses:
  request-patch-opportunity: ../types/requests/patch-opportunity.raml
  response-patch-opportunity: ../types/responses/patch-opportunity.raml
displayName: updateOpportunity
description: |
  This trait represents the behavior of updating an opportunity in the Service Cloud system.
  It can be used as a reusable component in the API definition.
body:
  application/json:
    type: request-patch-opportunity.patch-opportunity
    example: !include ../examples/requests/patch-opportunity.json
responses:
  200:
    body:
      application/json:
        #type: response-patch-opportunity.patch-opportunity
        example: !include ../examples/responses/patch-opportunity.json