#%RAML 1.0 Trait

uses:
  response-get-all-cases: ../types/responses/get-all-cases.raml

displayName: getAllCasesDetails
description: Obtém todos os casos para o e-mail fornecido.
queryParameters:
  page:
    type: integer
    example: 1
    description: Página atual
  limit?:
    type: integer
    example: 20
    description: Limite de objetos por página
responses: 
  200:
    body:
      application/json:
        type: response-get-all-cases.get-all-cases
        example: !include ../examples/responses/get-all-cases.json