#%RAML 1.0 Trait

uses:
  request-patch-opportunity: ../types/requests/patch-opportunity.raml
  response-patch-opportunity:

body:
  application/json:
    type: request-patch-opportunity.patch-opportunity
    example: !include ../examples/requests/patch-opportunity.json
responses:
  