#%RAML 1.0 Trait

uses:
  response-get-all-contacts: ../types/responses/get-all-contacts.raml
displayName: getAllContactDetails
description: Get customer contact information for the given search parameter.
queryParameters:
  page:
    type: integer
    example: 1
    description: Current page
  limit?:
    type: integer
    example: 20
    description: Limit of objects per page
responses: 
  200:
    body: 
      application/json:
        type: response-get-all-contacts.get-all-contacts
        example: !include ../examples/responses/get-all-contacts.json