#%RAML 1.0 Trait

uses:
  response-get-all-cases: ../types/responses/get-all-opportunitys.raml
displayName: getAllCasesDetails
description: Get all cases for the given e-mail.
queryParameters:
  page:
    type: integer
    example: 1
    description: Current page
  limit?:
    type: integer
    example: 20
    description: Limit of objects per page
responses: 
  200:
    body:
      application/json:
        type: response-get-all-cases.get-all-cases
        example: !include ../examples/responses/get-all-opportunitys.json