#%RAML 1.0 Trait

uses:
  put-contact-request: ../types/requests/put-contact.raml
  put-contact-response: ../types/responses/put-contact.raml
displayName: updateContactDetails
description: Updates a contact's account in the service cloud system.
body:
  type: put-contact-request.put-contact
  example: !include ../examples/requests/put-contact.json
responses:
  200:
    body:
      application/json:
        type: put-contact-response.put-contact
        example: !include ../examples/responses/put-contact.json

uriParameters:
  contactId:
    description: Specifies the unique identifier for the contact's account.
    example: 0034x00001I71rbAAB
    type: string