#%RAML 1.0 Trait

uses:
  global-resources-fragments: /exchange_modules/f8f9abd2-10a0-400f-bb5b-60cbd5b8cb29/global-resources-fragments/1.0.0/global-resources-fragments.raml
  get-all-contacts: ../types/responses/get-all-contacts.raml

is: [ global-resources-fragments.ErrorResponses ]
securedBy:  
- global-resources-fragments.client-enforcement
- global-resources-fragments.basic-authentication
- global-resources-fragments.oauth_2_0
put:
  displayName: updateContactDetails
  description: Updates a contact's account in the service cloud system.
  body:
    type: Contact
  responses:
    200:
      body:
        application/json:
          example: !include /exchange_modules/f8f9abd2-10a0-400f-bb5b-60cbd5b8cb29/accelerator-salesforce-resources/1.0.1/examples/common/UpdateResponseExample.raml

uriParameters:
  contactId:
    description: Specifies the unique identifier for the contact's account.
    example: 0034x00001I71rbAAB
    type: string
