#%RAML 1.0 NamedExample
value: {
  "firstName": "Diane",
  "lastName": "Deluna",
  "email": "dianedeluna@email.com",
  "homePhone": "673-657-1633",
  "mobilePhone": "302-418-1924",
  "businessPhone": "172-386-9372",
  "id": "abkGgOEr01x9PChQpmC4AjiOGe",
  "name": "Diane Deluna",
  "customerNo": "00003501"
}