#%RAML 1.0 NamedExample
value: {
  "count": 1,
  "hits": [
    {
      "_type": "order",
      "adjusted_merchandize_total_tax": 19.65,
      "adjusted_shipping_total_tax": 0.50,
      "billing_address": {
        "_type": "order_address",
        "address1": "3357 Benedum Drive",
        "city": "West Nyack",
        "country_code": "US",
        "first_name": "Diane",
        "full_name": "Diane Deluna",
        "id": "39b38fceb0f4f2bb92d5588689",
        "last_name": "Deluna",
        "phone": "845-304-6598",
        "postal_code": "10994",
        "state_code": "NY"
      },
      "confirmation_status": "confirmed",
      "created_by": "Customer",
      "creation_date": "2022-09-28T13:52:23.000Z",
      "currency": "USD",
      "customer_info": {
        "_type": "customer_info",
        "customer_id": "abkGgOEr01x9PChQpmC4AjiOGe",
        "customer_name": "Diane Deluna",
        "customer_no": "00003501",
        "email": "dianedeluna@email.com"
      },
      "customer_name": "Diane Deluna",
      "export_status": "ready",
      "guest": false,
      "last_modified": "2022-09-28T13:53:28.000Z",
      "merchandize_total_tax": 19.65,
      "notes": {
        "_type": "simple_link",
        "link": "https://zzrb-101.dx.commercecloud.salesforce.com/s/RefArch/dw/shop/v22_6/orders/00002501/notes"
      },
      "order_no": "00002501",
      "order_token": "gJyMbdYT7zM59A8dZrVEYMu9ttUu8_3sjD8sDgN47so",
      "order_total": 423.12,
      "payment_instruments": [
        {
          "_type": "order_payment_instrument",
          "amount": 423.12,
          "payment_card": {
            "_type": "payment_card",
            "card_type": "Visa",
            "credit_card_expired": false,
            "credit_card_token": "oy6jvqagdtr",
            "expiration_month": 5,
            "expiration_year": 2025,
            "holder": "Diane Deluna",
            "masked_number": "************1281",
            "number_last_digits": "1281"
          },
          "payment_instrument_id": "15e7112a67a7747fc28b14f3b1",
          "payment_method_id": "CREDIT_CARD"
        }
      ],
      "payment_status": "not_paid",
      "product_items": [
        {
          "_type": "product_item",
          "adjusted_tax": 9.65,
          "base_price": 192.99,
          "bonus_product_line_item": false,
          "gift": false,
          "item_id": "812ab7f61e6c86d673302d11c9",
          "item_text": "Garmin GPS 60™ Portable GPS Unit",
          "option_items": [
            {
              "_type": "option_item",
              "adjusted_tax": 0.00,
              "base_price": 0.00,
              "bonus_product_line_item": false,
              "gift": false,
              "item_id": "72e7d874cefa151f7c9e1bf14c",
              "item_text": "Extended Warranty: None",
              "option_id": "gpsWarranty",
              "option_value_id": "000",
              "price": 0.00,
              "price_after_item_discount": 0.00,
              "price_after_order_discount": 0.00,
              "product_id": "000",
              "product_name": "Extended Warranty: None",
              "quantity": 1,
              "shipment_id": "me",
              "tax": 0.00,
              "tax_basis": 0.00,
              "tax_class_id": "standard",
              "tax_rate": 0.05
            }
          ],
          "price": 192.99,
          "price_after_item_discount": 192.99,
          "price_after_order_discount": 192.99,
          "product_id": "garmin-gps-60M",
          "product_name": "Garmin GPS 60™ Portable GPS Unit",
          "quantity": 1,
          "shipment_id": "me",
          "tax": 9.65,
          "tax_basis": 192.99,
          "tax_class_id": "standard",
          "tax_rate": 0.05
        },
        {
          "_type": "product_item",
          "adjusted_tax": 10.00,
          "base_price": 199.99,
          "bonus_product_line_item": false,
          "gift": false,
          "item_id": "34c09f0f924a1234cec280a24f",
          "item_text": "Nintendo Wii™ Game Console",
          "option_items": [
            {
              "_type": "option_item",
              "adjusted_tax": 0.00,
              "base_price": 0.00,
              "bonus_product_line_item": false,
              "gift": false,
              "item_id": "86a0d0a46765da2fd87f6a2617",
              "item_text": "Extended Warranty: None",
              "option_id": "consoleWarranty",
              "option_value_id": "000",
              "price": 0.00,
              "price_after_item_discount": 0.00,
              "price_after_order_discount": 0.00,
              "product_id": "000",
              "product_name": "Extended Warranty: None",
              "quantity": 1,
              "shipment_id": "me",
              "tax": 0.00,
              "tax_basis": 0.00,
              "tax_class_id": "standard",
              "tax_rate": 0.05
            }
          ],
          "price": 199.99,
          "price_after_item_discount": 199.99,
          "price_after_order_discount": 199.99,
          "product_id": "nintendo-wii-consoleM",
          "product_name": "Nintendo Wii™ Game Console",
          "quantity": 1,
          "shipment_id": "me",
          "tax": 10.00,
          "tax_basis": 199.99,
          "tax_class_id": "standard",
          "tax_rate": 0.05
        }
      ],
      "product_sub_total": 392.98,
      "product_total": 392.98,
      "shipments": [
        {
          "_type": "shipment",
          "adjusted_merchandize_total_tax": 19.65,
          "adjusted_shipping_total_tax": 0.50,
          "gift": false,
          "merchandize_total_tax": 19.65,
          "product_sub_total": 392.98,
          "product_total": 392.98,
          "shipment_id": "me",
          "shipment_no": "00012501",
          "shipment_total": 423.12,
          "shipping_address": {
            "_type": "order_address",
            "address1": "3357 Benedum Drive",
            "city": "West Nyack",
            "country_code": "US",
            "first_name": "Diane",
            "full_name": "Diane Deluna",
            "id": "8f094966825bdca6d398a809e8",
            "last_name": "Deluna",
            "phone": "845-304-6598",
            "postal_code": "10994",
            "state_code": "NY"
          },
          "shipping_method": {
            "_type": "shipping_method",
            "description": "Order received within 7-10 business days",
            "id": "001",
            "name": "Ground",
            "price": 9.99,
            "c_estimatedArrivalTime": "7-10 Business Days"
          },
          "shipping_status": "not_shipped",
          "shipping_total": 9.99,
          "shipping_total_tax": 0.50,
          "tax_total": 20.15
        }
      ],
      "shipping_items": [
        {
          "_type": "shipping_item",
          "adjusted_tax": 0.50,
          "base_price": 9.99,
          "item_id": "f93d449eed6b1b96319fb5d403",
          "item_text": "Shipping",
          "price": 9.99,
          "price_after_item_discount": 9.99,
          "shipment_id": "me",
          "tax": 0.50,
          "tax_basis": 9.99,
          "tax_class_id": "standard",
          "tax_rate": 0.05
        }
      ],
      "shipping_status": "not_shipped",
      "shipping_total": 9.99,
      "shipping_total_tax": 0.50,
      "site_id": "RefArch",
      "status": "open",
      "taxation": "net",
      "tax_total": 20.15,
      "c_at_export_status": false
    }
  ],
  "start": 0,
  "total": 1
}