#%RAML 1.0 DataType
displayName: Profiles response
type: object
properties:
    cases:
      type: object
      properties:
        page: integer
        limit?: integer
    orders:
      type: object
      properties:
        page: integer
        limit?: integer
    profile: !include Profile.raml
examples: 
  SummaryRequestExample: !include ../../examples/common/SummaryRequestExample.raml