#%RAML 1.0 Library

types:
  patch-opportunity:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
          description: O ID da oportunidade.
          required: false
        accountId:
          type: string
          description: O ID da conta associada à oportunidade.
          required: false
        recordTypeId:
          type: string
          description: O ID do tipo de registro da oportunidade.
          required: false
        name:
          type: string
          description: O nome da oportunidade.
          required: false
        description:
          type: string
          description: A descrição da oportunidade.
          required: false
        stageName:
          type: string
          description: O estágio atual da oportunidade.
          required: false
          enum: 
            - Qualification
            - Needs Analysis
            - Proposal
            - Negotiation
            - Closed Won
            - Closed Lost
            - Presentation
            - Product Testing
            - Evaluation
            - Results Commercial Proposal
            - Closed No Decision
            - Probe Presentation
            - Prospect Pool new
            - Closed Won Opportunity
            - Closed Lost Opportunity
        amount:
          type: integer
          description: O valor da oportunidade.
          required: false
        probability:
          type: integer
          description: A probabilidade de fechamento da oportunidade.
          required: false
        closeDate:
          type: string
          description: A data de fechamento da oportunidade.
          required: false
        OpportunityType:
          type: string
          description: O tipo de oportunidade.
          required: false
          enum: 
            - Existing Business
            - New Business
            - Acquire
            - Acquire - New Account
            - Air Care - 30-day Free Trial
            - Best Brands 2P
            - Best Brands 3P
            - Best Brands - Elite
            - Best Brands - Silver
            - Churn
            - Decline
            - Expansion
            - Guaranteed Trial
            - Handled By Distributor Only
            - JACKSON PPE - Free Trial Request
        nextStep:
          type: string
          description: O próximo passo planejado para a oportunidade.
          required: false
        leadSource:
          type: string
          description: A fonte de leads da oportunidade.
          required: false
          enum: 
            - Advertisement
            - Customer Event
            - Employee Referral
            - External Referral
            - Google AdWords
            - Other
            - Partner
            - Purchased List
            - Trade Show
            - Webinar
            - Website
            - AI
            - Base de datos Distribuidor
            - BizCard Scanner
            - Brand awarness
            - Brand seen in bathroom
            - Brand seen in delivery cars
        forecastCategoryName:
          type: string
          description: O nome da categoria de previsão da oportunidade.
          required: false
          enum: 
            - Omitted
            - Pipeline
            - Best Case
            - Commit
            - Closed
        campaignId:
          type: string
          description: O ID da campanha associada à oportunidade.
          required: false
        pricebook2Id:
          type: string
          description: O ID do catálogo de preços associado à oportunidade.
          required: false
        ownerId:
          type: string
          description: O ID do proprietário da oportunidade.
          required: false
        syncedQuoteId:
          type: string
          description: O ID da cotação sincronizada com a oportunidade.
          required: false
        contractId:
          type: string
          description: O ID do contrato associado à oportunidade.
          required: false
        budgetConfirmed:
          type: boolean
          description: Indica se o orçamento da oportunidade foi confirmado.
          required: false
        discoveryCompleted:
          type: boolean
          description: Indica se a descoberta da oportunidade foi concluída.
          required: false
        roiAnalysisCompleted:
          type: boolean
          description: Indica se a análise de ROI da oportunidade foi concluída.
          required: false
        lossReason:
          type: string
          description: O motivo da perda da oportunidade.
          required: false
          enum: 
            - Lost to Competitor
            - No Budget / Lost Funding
            - No Decision / Non-Responsive
            - Price
            - Other
        gbPurchaseStartDate:
          type: string
          description: A data de início da compra global da oportunidade.
          required: false