#%RAML 1.0 Library

types:
  put-contact:
    type: object
    properties:
      email:
        type: string
        example: dianedeluna@email.com
        required: false
      firstName:
        type: string
        example: Diane
        required: false
      id:
        type: string
        example: 0034x00001I71rbAAB
        required: false
      lastName:
        type: string
        example: Deluna
        required: false
      mobilePhone:
        type: string
        example: 803-283-1927
        required: false
      phone:
        type: string
        example: 845-304-6598
        required: false
