#%RAML 1.0 DataType
type: object
displayName: Order details
properties:
  _type:
    type: string
    required: false
  adjusted_merchandize_total_tax:
    type: number
    required: false
  adjusted_shipping_total_tax:
    type: number
    required: false
  billing_address:
    type: object
    properties:
      _type:
        type: string
        required: false
      address1:
        type: string
        required: false
      city:
        type: string
        required: false
      country_code:
        type: string
        required: false
      first_name:
        type: string
        required: false
      full_name:
        type: string
        required: false
      id:
        type: string
        required: false
      last_name:
        type: string
        required: false
      phone:
        type: string
        required: false
      postal_code:
        type: string
        required: false
      state_code:
        type: string
        required: false
  confirmation_status:
    type: string
    required: false
  created_by:
    type: string
    required: false
  creation_date:
    type: datetime
    required: false
  currency:
    type: string
    required: false
  customer_info:
    type: object
    properties:
      _type:
        type: string
        required: false
      customer_id:
        type: string
        required: false
      customer_name:
        type: string
        required: false
      customer_no:
        type: string
        required: false
      email:
        type: string
        required: false
  customer_name:
    type: string
    required: false
  export_status:
    type: string
    required: false
  guest:
    type: boolean
    required: false
  last_modified:
    type: datetime
    required: false
  merchandize_total_tax:
    type: number
    required: false
  notes:
    type: object
    properties:
      _type:
        type: string
        required: false
      link:
        type: string
        required: false
  order_no:
    type: string
    required: false
  order_token:
    type: string
    required: false
  order_total:
    type: number
    required: false
  payment_instruments:
    type: array
    items:
      type: object
      properties:
        _type:
          type: string
          required: false
        amount:
          type: number
          required: false
        payment_card:
          type: object
          properties:
            _type:
              type: string
              required: false
            card_type:
              type: string
              required: false
            credit_card_expired:
              type: boolean
              required: false
            credit_card_token:
              type: string
              required: false
            expiration_month:
              type: integer
              required: false
            expiration_year:
              type: integer
              required: false
            holder:
              type: string
              required: false
            masked_number:
              type: string
              required: false
            number_last_digits:
              type: string
              required: false
        payment_instrument_id:
          type: string
          required: false
        payment_method_id:
          type: string
          required: false
  payment_status:
    type: string
    required: false
  product_items:
    type: array
    items:
      type: object
      properties:
        _type:
          type: string
          required: false
        adjusted_tax:
          type: number
          required: false
        base_price:
          type: number
          required: false
        bonus_product_line_item:
          type: boolean
          required: false
        gift:
          type: boolean
          required: false
        item_id:
          type: string
          required: false
        item_text:
          type: string
          required: false
        option_items:
          type: array
          items:
            type: object
            properties:
              _type:
                type: string
                required: false
              adjusted_tax:
                type: integer
                required: false
              base_price:
                type: integer
                required: false
              bonus_product_line_item:
                type: boolean
                required: false
              gift:
                type: boolean
                required: false
              item_id:
                type: string
                required: false
              item_text:
                type: string
                required: false
              option_id:
                type: string
                required: false
              option_value_id:
                type: string
                required: false
              price:
                type: integer
                required: false
              price_after_item_discount:
                type: integer
                required: false
              price_after_order_discount:
                type: integer
                required: false
              product_id:
                type: string
                required: false
              product_name:
                type: string
                required: false
              quantity:
                type: integer
                required: false
              shipment_id:
                type: string
                required: false
              tax:
                type: integer
                required: false
              tax_basis:
                type: integer
                required: false
              tax_class_id:
                type: string
                required: false
              tax_rate:
                type: number
                required: false
        price:
          type: number
          required: false
        price_after_item_discount:
          type: number
          required: false
        price_after_order_discount:
          type: number
          required: false
        product_id:
          type: string
          required: false
        product_name:
          type: string
          required: false
        quantity:
          type: integer
          required: false
        shipment_id:
          type: string
          required: false
        tax:
          type: number
          required: false
        tax_basis:
          type: number
          required: false
        tax_class_id:
          type: string
          required: false
        tax_rate:
          type: number
          required: false
  product_sub_total:
    type: number
    required: false
  product_total:
    type: number
    required: false
  shipments:
    type: array
    items:
      type: object
      properties:
        _type:
          type: string
          required: false
        adjusted_merchandize_total_tax:
          type: number
          required: false
        adjusted_shipping_total_tax:
          type: number
          required: false
        gift:
          type: boolean
          required: false
        merchandize_total_tax:
          type: number
          required: false
        product_sub_total:
          type: number
          required: false
        product_total:
          type: number
          required: false
        shipment_id:
          type: string
          required: false
        shipment_no:
          type: string
          required: false
        shipment_total:
          type: number
          required: false
        shipping_address:
          type: object
          properties:
            _type:
              type: string
              required: false
            address1:
              type: string
              required: false
            city:
              type: string
              required: false
            country_code:
              type: string
              required: false
            first_name:
              type: string
              required: false
            full_name:
              type: string
              required: false
            id:
              type: string
              required: false
            last_name:
              type: string
              required: false
            phone:
              type: string
              required: false
            postal_code:
              type: string
              required: false
            state_code:
              type: string
              required: false
        shipping_method:
          type: object
          properties:
            _type:
              type: string
              required: false
            description:
              type: string
              required: false
            id:
              type: string
              required: false
            name:
              type: string
              required: false
            price:
              type: number
              required: false
            c_estimatedArrivalTime:
              type: string
              required: false
        shipping_status:
          type: string
          required: false
        shipping_total:
          type: number
          required: false
        shipping_total_tax:
          type: number
          required: false
        tax_total:
          type: number
          required: false
  shipping_items:
    type: array
    items:
      type: object
      properties:
        _type:
          type: string
          required: false
        adjusted_tax:
          type: number
          required: false
        base_price:
          type: number
          required: false
        item_id:
          type: string
          required: false
        item_text:
          type: string
          required: false
        price:
          type: number
          required: false
        price_after_item_discount:
          type: number
          required: false
        shipment_id:
          type: string
          required: false
        tax:
          type: number
          required: false
        tax_basis:
          type: number
          required: false
        tax_class_id:
          type: string
          required: false
        tax_rate:
          type: number
          required: false
  shipping_status:
    type: string
    required: false
  shipping_total:
    type: number
    required: false
  shipping_total_tax:
    type: number
    required: false
  site_id:
    type: string
    required: false
  status:
    type: string
    required: false
  taxation:
    type: string
    required: false
  tax_total:
    type: number
    required: false
  c_at_export_status:
    type: boolean
    required: false
examples: !include ../../examples/commerce/OrderExample.raml